version: '3.6'
services:
  idp:
    container_name: idp
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      FALLBACK_REDIRECT: ${OAUTH_FALLBACK_REDIRECT-/}
#    ports:
#      - 82:81
networks:
  dc-net:
    external: true