version: '3.6'
services:
  idp:
    container_name: idp
    restart: always
    build: .
    networks:
      - dc-net
    environment:
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: idp
      NAMESPACE: dev-dc
#    ports:
#      - 82:80
networks:
  dc-net:
    external: true