version: '3.6'
services:
  idp:
    container_name: idp
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: idp

      CONTAINER_PORT: ${CONTAINER_PORT-80}
      OUTER_PORT: ${OUTER_PORT-80}
      LOGOTIPIWE_GMAIL_ID: ${LOGOTIPIWE_GMAIL_ID}
      G_OAUTH_CLIENT_SECRET: ${G_OAUTH_CLIENT_SECRET}
      SUBPATH: ${SUBPATH-/oauth2}
      OUTER_SCHEME : ${OUTER_SCHEME}
      OUTER_HOST : ${OUTER_HOST}
      FALLBACK_REDIRECT: ${OAUTH_FALLBACK_REDIRECT-/}
#    ports:
#      - 82:81
networks:
  dc-net:
    external: true