version: '3.6'
services:
  idp:
    container_name: idp
    restart: always
    build: .
    networks:
      - dc-net
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: idp

      CONTAINER_PORT: 80
      OUTER_PORT: 80
      LOGOTIPIWE_GMAIL_ID: ${LOGOTIPIWE_GMAIL_ID}
      G_OAUTH_CLIENT_SECRET: ${G_OAUTH_CLIENT_SECRET}
      SUBPATH: ${SUBPATH-/oauth2}
      OUTER_SCHEME: http
      OUTER_HOST: localhost
      FALLBACK_REDIRECT: ${OAUTH_FALLBACK_REDIRECT-/}
      GOOGLE_AUTO_AUTH: 1
      LOGOTIPIWE_DC_ID: ${LOGOTIPIWE_DC_ID}
      M_TOKEN: ${M_TOKEN}
#      CONFIG_SERVER_URL: http://config_server
#      SERVICE_NAME: pixel-battle-back
#      NAMESPACE: dev-dc
#    ports:
#      - 82:80
networks:
  dc-net:
    external: true